p_name = input()
p_price = input()
p_weight = input()
p_money = input()
p_sum = int(p_money) - int(p_price) * int(p_weight)
p_pr_w = int(p_price) * int(p_weight)
print("Чек")
print(p_name + " - " + str(p_weight) + "кг" + " - " + str(p_price) + "руб/кг")
print("Итого: " + str(p_pr_w) + "руб")
print("Внесено: " + str(p_money) + "руб")
print("Сдача: " + str(p_sum) + "руб")